name: Build Executables

on:
  # push:
    # branches:
    #   - 'main'
    #   - 'releases/**'
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies using uv
        run: |
          python -m ensurepip
          python -m uv pip install nuitka ordered-set zstandard imageio
          python -m uv pip install -e .

      - name: Build Executable with Nuitka windows
        uses: Nuitka/Nuitka-Action@main
        if: "${{ runner.os == 'windows' }}"
        with:
          nuitka-version: main
          script-name: src/contest_scoreboard_monitor
          enable-plugins: tk-inter
          disable-console: false
          output-dir: contest_scoreboard_monitor
          windows-icon-from-ico: icon.png
          mode: standalone

      - name: Build Executable with Nuitka macos
        uses: Nuitka/Nuitka-Action@main
        if: "${{ runner.os == 'macos' }}"
        with:
          nuitka-version: main
          script-name: src/contest_scoreboard_monitor
          enable-plugins: tk-inter
          disable-console: false
          macos-app-name: ContestScoreboardMonitor.app
          macos-app-icon: icon.png
          mode: standalone


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            build/*.dist/**/*
            build/*/**/*
          include-hidden-files: true
